// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjBv6fOicm0jo5_w8dHJtMujCcfR7J7Ww',
    appId: '1:264695457696:web:aec4e88717def4261ce6c5',
    messagingSenderId: '264695457696',
    projectId: 'ruang-bicara-96ea5',
    authDomain: 'ruang-bicara-96ea5.firebaseapp.com',
    storageBucket: 'ruang-bicara-96ea5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBbOjvyvs6PJdEI5U72XgSCwKzXk1Hi_s',
    appId: '1:264695457696:android:f489660b75ee3b2a1ce6c5',
    messagingSenderId: '264695457696',
    projectId: 'ruang-bicara-96ea5',
    storageBucket: 'ruang-bicara-96ea5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfhMoU0BigxYs9NmcHo2XZmT__61xHopM',
    appId: '1:264695457696:ios:29afe55b1db310e71ce6c5',
    messagingSenderId: '264695457696',
    projectId: 'ruang-bicara-96ea5',
    storageBucket: 'ruang-bicara-96ea5.appspot.com',
    iosBundleId: 'com.example.ruangBicara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfhMoU0BigxYs9NmcHo2XZmT__61xHopM',
    appId: '1:264695457696:ios:29afe55b1db310e71ce6c5',
    messagingSenderId: '264695457696',
    projectId: 'ruang-bicara-96ea5',
    storageBucket: 'ruang-bicara-96ea5.appspot.com',
    iosBundleId: 'com.example.ruangBicara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjBv6fOicm0jo5_w8dHJtMujCcfR7J7Ww',
    appId: '1:264695457696:web:217ddd6ed4a9d2871ce6c5',
    messagingSenderId: '264695457696',
    projectId: 'ruang-bicara-96ea5',
    authDomain: 'ruang-bicara-96ea5.firebaseapp.com',
    storageBucket: 'ruang-bicara-96ea5.appspot.com',
  );
}
